In [16]:
# 1.交换一个3*4的数组的后两行
import numpy as np
arr1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr1)
arr=np.array([[1,1,1,1]])
arr[0]=arr1[2]
arr1[2]=arr1[1]
arr1[1]=arr[0]
print(arr1)

import numpy as np
a1=np.arange(0,12).reshape(3,4)
print(a1)
a1[[1,2],:]=a1[[2,1],:]
print(a1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 9 10 11 12]
 [ 5  6  7  8]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 8  9 10 11]
 [ 4  5  6  7]]


In [20]:
# 2.交换两个3*4的数组的第[3]列
import numpy as np
arr1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr2=np.array([[0,0,90,0],[1,1,95,1],[2,2,100,2]])
print(arr1)
print(arr2)
arr=np.array([[1],[1],[1]])
arr[:,0]=arr1[:,2]
arr1[:,2]=arr2[:,2]
arr2[:,2]=arr[:,0]
print(arr1)
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[  0   0  90   0]
 [  1   1  95   1]
 [  2   2 100   2]]
[[  1   2  90   4]
 [  5   6  95   8]
 [  9  10 100  12]]
[[ 0  0  3  0]
 [ 1  1  7  1]
 [ 2  2 11  2]]


In [38]:
# 3.打印杨辉三角的前10行
# 1
# 1  1
# 1  2  1
# 1  3  3  1
# 1  4  6  4  1
# 1  5  10 10 5 1
arr3=np.eye(10,dtype=np.int32)
arr3[:,0]=1
for i in range(1,10):
    for j in range(1,i):
            arr3[i][j]=arr3[i-1][j-1]+arr3[i-1][j]
print(arr3)


[[  1   0   0   0   0   0   0   0   0   0]
 [  1   1   0   0   0   0   0   0   0   0]
 [  1   2   1   0   0   0   0   0   0   0]
 [  1   3   3   1   0   0   0   0   0   0]
 [  1   4   6   4   1   0   0   0   0   0]
 [  1   5  10  10   5   1   0   0   0   0]
 [  1   6  15  20  15   6   1   0   0   0]
 [  1   7  21  35  35  21   7   1   0   0]
 [  1   8  28  56  70  56  28   8   1   0]
 [  1   9  36  84 126 126  84  36   9   1]]
