In [2]:
# 1. 创建一个4*4数组，元素值从1~16，
#    1) 将该数组纵向分割成两个数组A、B，
#    2) 再组合生成一个新数组形式为[B A B]
import numpy as np
a=np.arange(1,17,1).reshape(4,4)
print(a)
(A,B)=np.vsplit(a,2)
print(A)
print(B)
C=np.hstack((B,A,B))
print(C)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]
[[ 9 10 11 12  1  2  3  4  9 10 11 12]
 [13 14 15 16  5  6  7  8 13 14 15 16]]


In [35]:
# 2. 创建一个3*4的数组，元素服从均匀分布，
#    1) 沿横轴计算数组的和、均值、标准差、方差、最小值、最大值、所有元素的和、所有元素的积。
#    2) 对数组按纵轴进行排序，打印结果
import random
a=np.random.uniform(1,10,size=12).reshape(3,4)
print('元素服从均匀分布的3*4的数组：\n',a)
sum1=a.sum(axis=1)
print('沿着横轴计算数组的和：\n',sum1)
mean1=a.mean(axis=1)
print('沿着横轴计算数组的均值：\n',mean1)
std1=a.std(axis=1)
print('沿着横轴计算数组的标准差：\n',std1)
var1=a.var(axis=1)
print('沿着横轴计算数组的方差：\n',var1)
min1=a.min(axis=1)
print('沿着横轴计算数组的最小值：\n',min1)
max1=a.max(axis=1)
print('沿着横轴计算数组的最大值：\n',max1)
cumsum1=a.cumsum()
print('计算数组的所有元素的和：\n',cumsum1[-1])
cumprod1=a.cumprod()
print('计算数组的所有元素的积：\n',cumprod1[-1])
a.sort(axis=0)
print('纵轴排序结果：\n',a)


元素服从均匀分布的3*4的数组：
 [[4.11300894 5.51968779 1.1936752  4.55219996]
 [7.07870994 9.83615814 4.40158939 1.52412703]
 [1.38877288 1.43117834 7.60709401 2.8738758 ]]
沿着横轴计算数组的和：
 [15.37857189 22.8405845  13.30092103]
沿着横轴计算数组的均值：
 [3.84464297 5.71014613 3.32523026]
沿着横轴计算数组的标准差：
 [1.61292145 3.08755643 2.54339232]
沿着横轴计算数组的方差：
 [2.60151561 9.53300468 6.46884448]
沿着横轴计算数组的最小值：
 [1.1936752  1.52412703 1.38877288]
沿着横轴计算数组的最大值：
 [5.51968779 9.83615814 7.60709401]
计算数组的所有元素的和：
 51.52007743129908
计算数组的所有元素的积：
 2503823.6626314074
纵轴排序结果：
 [[1.38877288 1.43117834 1.1936752  1.52412703]
 [4.11300894 5.51968779 4.40158939 2.8738758 ]
 [7.07870994 9.83615814 7.60709401 4.55219996]]


In [36]:
# 3. 创建两个2*3的矩阵A、B，元素为5~10之间的随机浮点数，
#    1) 计算两个矩阵相加、相减、相乘、对应元素相乘、相除的值
A=np.random.uniform(5,10,size=[6]).reshape(2,3)
B=np.random.uniform(5,10,size=[6]).reshape(2,3)
print('1)','-'*30)
print('A的值为：\n',A)
print('B的值为：\n',B)
print('两个矩阵相加的值为：\n',A+B)
print('两个矩阵相减的值为：\n',A-B)
print('两个矩阵相乘的值为：\n',A*B)
print('两个矩阵对应元素相乘的值为：\n',np.multiply(A,B))
print('两个矩阵相除的值的值为：\n',A/B)
#    2) 比较两个矩阵的大小，若A中所有元素都大于B，打印"A>B"，若A中任意元素大于B，打印"A_part > B"
print('2)','-'*30)
if (A>B).all():
    print('A>B')
elif (A>B).any():
    print('A_part>B')
#    3) 去掉两个矩阵中重复的元素   
print('3)','-'*30)
A_1=np.unique(A)
B_1=np.unique(B)
print(A_1,B_1)
#    4) 将矩阵A按行展开，将矩阵B按列展开
print('4)','-'*30)
A_2=A.flatten()
A_3=A.ravel()
B_2=B.flatten('F')
print(A_2)
print(A_3)
print(B_2)

1) ------------------------------
A的值为：
 [[8.41786604 6.0676153  6.52500027]
 [5.43477028 9.98944997 5.14285859]]
B的值为：
 [[6.5352906  5.15665    6.21604423]
 [6.19821956 6.89038073 9.12876725]]
两个矩阵相加的值为：
 [[14.95315665 11.2242653  12.7410445 ]
 [11.63298984 16.87983071 14.27162584]]
两个矩阵相减的值为：
 [[ 1.88257544  0.91096529  0.30895603]
 [-0.76344927  3.09906924 -3.98590866]]
两个矩阵相乘的值为：
 [[55.01320086 31.28856842 40.55969026]
 [33.68589944 68.83111363 46.94795906]]
两个矩阵对应元素相乘的值为：
 [[55.01320086 31.28856842 40.55969026]
 [33.68589944 68.83111363 46.94795906]]
两个矩阵相除的值的值为：
 [[1.288063   1.17665835 1.049703  ]
 [0.87682765 1.44976749 0.56336835]]
2) ------------------------------
A_part>B
3) ------------------------------
[5.14285859 5.43477028 6.0676153  6.52500027 8.41786604 9.98944997] [5.15665    6.19821956 6.21604423 6.5352906  6.89038073 9.12876725]
4) ------------------------------
[8.41786604 6.0676153  6.52500027 5.43477028 9.98944997 5.14285859]
[8.41786604 6.0676153  6.52500027 5.